### ISSUE TITLE
Create engine

### ISSUE THREAD

**Issue by VladMatyunin** [chupakabra1996/ansible-vagrant-spring#1]
Create real motherFucker engine to fuck the kyrsovaya

**Comment by ramsafin** [comment]
I'm working on it, thank you! By the way, you can contribute some time....

**Comment by VladMatyunin** [comment]
Yeah, sure! Just wait till wed. 31 may)

24 мая 2017 г. 10:55 PM пользователь "Ramil" <notifications@github.com>
написал:
